import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8"></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      </head>
      <body className={montserrat.className}>
        <Providers>
          <main className="light text-foreground bg-background-700">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
